### ISSUE TITLE
Get's Quarantined as a Virus on windows.

### ISSUE THREAD

**Issue by ErebusAres** [Meridanus/fabric_xp_storage_1.18#16]
Installing this mod as part of the Deathdusk modpack, and it's caught as a Trojan Virus.
ETA: Happens when making the server, on windows, and installing the modpack on PC (Windows 11)
![xp_obelisk_virusimg](https://user-images.githubusercontent.com/3603760/166859296-dda892c1-3fd9-4be8-b381-f14e9f7de2bf.png)

**Comment by Meridanus** [comment]
Where does the File come from? CurseForge? 
Don't know how this could happen, as first step I removed this alpha Jar From The Download Page

**Comment by ErebusAres** [comment]
Yes we got the modpack via curseforge.

**Comment by ErebusAres** [comment]
I'm assuming its just a false positive.
also, its not my end as both me and my friend, who is attempting to host deathdusk found it.
