### ISSUE TITLE
[Suggestion] Experience Transfer Tool

### ISSUE THREAD

**Issue by xanthian** [Meridanus/fabric_xp_storage_1.18#2]
It would be good if you there was a slight texture change when swapping between modes to save having to check your bag to see.

![image](https://user-images.githubusercontent.com/7688001/146923143-992fc6e2-394a-4f5d-a79a-e6019ef6a254.png)
![image](https://user-images.githubusercontent.com/7688001/146923231-0e33f99f-ec9f-4079-9969-1e13d72040f6.png)

Forgive my poor attempts, it was just a mock up 😜

**Comment by Meridanus** [comment]
good idea, but which way should be the Icons?
Xp flow from Tank view:
- Player to Tank (+)
- Tank to Player (-)

or tho other way around?
Xp flow from Player view:
- Player to Tank (-)
- Tank to Player (+)

the item glow gives already a hint which mode is current active.

**Comment by xanthian** [comment]
Yes, fair point.
I'll leave that decision to you :D
