### ISSUE TITLE
Random Warning in log

### ISSUE THREAD

**Issue by xanthian** [Meridanus/fabric_xp_storage_1.18#3]
[Worker-Main-6/WARN]: Unable to resolve texture reference: #missing in xps:block/block_xp_obelisk_with_xp
[Worker-Main-6/WARN]: Unable to resolve texture reference: #missing in xps:block/block_xp_obelisk
[Worker-Main-6/WARN]: Unable to resolve texture reference: #missing in xps:item/block_xp_obelisk

Obviously nothing to be concerned about and no impact in game, but reporting for your attention.

Regards,

ps. the new tool graphic is great :)

**Comment by Meridanus** [comment]
Thanks man :D i appreciate this.

fixed ✔️
