### ISSUE TITLE
Command issues on 1.19.2.

### ISSUE THREAD

**Issue by Poke097** [Meridanus/fabric_xp_storage_1.18#35]
Hi! when joining the server with this mod it does this:

Joining the server and typing any command (example of /gamemode creative here) this appears in chat.
Cannot invoke "com.mojang.brigadier.CommandDispatcher.execute(String, Object)" because net.fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispatcher" is null

Now it fixes by joining a single-player world first then joining the server, but having to join a single-player world each time on launch just to use any commands is annoying and weird. 

To determine this mod was the issue, I did a binary search and concluded this mod was the one causing the issues.

**Comment by Meridanus** [comment]
hello,

Can you provide a crash report and a list of mods on which you play on?
I cant imagine that my mod does this... i modify none of command or chat things.

i try to take a look but i don't know if i can resolve that issue...

**Comment by Poke097** [comment]
https://user-images.githubusercontent.com/33227568/197660336-5af8075e-d274-4918-b13f-fc7d84a4233d.mp4

Here is the video showing I have my server up, and cannot initiate commands via the client.

**Comment by Poke097** [comment]
[latest.log](https://github.com/Meridanus/fabric_xp_storage_1.18/files/9856398/latest.log)
This is the latest log for the server-side of things, WITH your mods

**Comment by Poke097** [comment]
[latest.log](https://github.com/Meridanus/fabric_xp_storage_1.18/files/9856401/latest.log)
This is the latest log with the client-side WITH your mods

**Comment by Poke097** [comment]
https://user-images.githubusercontent.com/33227568/197660926-a88ae0a6-4d22-4a0f-ae74-1d8086ce583b.mp4

https://user-images.githubusercontent.com/33227568/197661005-8c8bbf57-661c-4fda-bf00-4d3467477b38.mp4


This is to show I had your mods in both the server and client when showing the issues above.

**Comment by Poke097** [comment]
https://user-images.githubusercontent.com/33227568/197661820-ec763775-079e-4e90-b707-ce8de6225b6e.mp4

Here is the video showing that commands work via client input WITHOUT your mods installed on client and server

**Comment by Poke097** [comment]
[latest.log](https://github.com/Meridanus/fabric_xp_storage_1.18/files/9856446/latest.log)

This is the latest log of the client side WITHOUT your mods

**Comment by Poke097** [comment]
[latest.log](https://github.com/Meridanus/fabric_xp_storage_1.18/files/9856448/latest.log)

Here is the latest log of the server side WITHOUT your mods

**Comment by Poke097** [comment]
https://user-images.githubusercontent.com/33227568/197662504-436d1329-22f1-4791-85cf-235b1cd30840.mp4


https://user-images.githubusercontent.com/33227568/197662518-f420ce8b-b7cd-44e4-9826-16113804dcf0.mp4

This is to show that I did not have your mods installed during the time of the second test when commands worked both on the client side or server side.

**Comment by Poke097** [comment]
I love love your mods capabilities, but hopefully you can figure out what the heck is going on so I can use it once again!

I wish you good luck in the search for the issue :)

**Comment by Meridanus** [comment]
thanks for the feedback, does the issue occur without the additions mod? maybe there lies the problem?

**Comment by Poke097** [comment]
Which one in specific? Additional Addtions?
or..?

**Comment by Meridanus** [comment]
xp_obelisk_additions maybe its the mixin

**Comment by Poke097** [comment]
Checking right now chief, be right back :D

**Comment by Poke097** [comment]
YOU WERE RIGHT! guess the additions messes with it :p

**Comment by Meridanus** [comment]
ok thanks maybe i'll find the issue

**Comment by Meridanus** [comment]
I read the logs and oh boy there are a lot of errors/warnings conflicts and failed mixings... I don't find any problem on my side and I hear about this issue for the first time. I take a deeper look and Test a little bit

**Comment by Poke097** [comment]
I basically just kept taking out mods until the issue stopped, legit had to go in one by one

**Comment by MKmods** [comment]
Ran into this issue as well on our server. Going back to a previous version of the xp obelisk mods fixed it.

Here's our modlist if you want it.
[mod list.txt](https://github.com/Meridanus/fabric_xp_storage_1.18/files/10147495/mod.list.txt)

**Comment by Meridanus** [comment]
Thanks for the list.
that's strange, some other mod interact with my mod. since stand alone this error don't occur and the mod does nothing with commands etc...

**Comment by Meridanus** [comment]
https://github.com/Meridanus/fabric_xp_storage_additions/issues/18
